trigger: none
 
resources:
  packages:
   - package: nodePackage
     type: Npm
     connection: gh-rg
     name: nugetTest/nodeapp
    #  version: 1.0.9
     trigger: true
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: hosted
       steps:
        - getPackage: nodePackage
