trigger: none
 
resources:
  packages:
   - package: nugetPackage
     type: Nuget
     connection: gh-rg
     name: nugetTest/OctocatApp
     version: 2.1.10
     trigger: true
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: rogoyal
       steps:
        - getPackage: nugetPackage
